// This file is automatically generated. Do not edit manually.

/// Contains all localization keys used in the application.
abstract class AppLang {
  AppLang._();

  // --- General ---
  static const String appName = "app_name";

  // --- Actions ---
  static const String actionsAcceptTerms = "actions.accept_terms";
  static const String actionsAdd = "actions.add";
  static const String actionsApply = "actions.apply";
  static const String actionsBack = "actions.back";
  static const String actionsBrowseFiles = "actions.browse_files";
  static const String actionsCancel = "actions.cancel";
  static const String actionsClear = "actions.clear";
  static const String actionsClose = "actions.close";
  static const String actionsConfirm = "actions.confirm";
  static const String actionsContinue = "actions.continue";
  static const String actionsCreate = "actions.create";
  static const String actionsCreateCopy = "actions.create_copy";
  static const String actionsCreateCopyError = "actions.create_copy_error";
  static const String actionsCreateCopySuccess = "actions.create_copy_success";
  static const String actionsDeclineOffer = "actions.decline_offer";
  static const String actionsDelete = "actions.delete";
  static const String actionsDone = "actions.done";
  static const String actionsDownload = "actions.download";
  static const String actionsDownloadDocument = "actions.download_document";
  static const String actionsEdit = "actions.edit";
  static const String actionsExportData = "actions.export_data";
  static const String actionsExportSummary = "actions.export_summary";
  static const String actionsFillDocument = "actions.fill_document";
  static const String actionsFinishProcess = "actions.finish_process";
  static const String actionsGetStartedNow = "actions.get_started_now";
  static const String actionsGoToAppSettings = "actions.go_to_app_settings";
  static const String actionsImportData = "actions.import_data";
  static const String actionsLearnMoreAbout = "actions.learn_more_about";
  static const String actionsLoadCopyError = "actions.load_copy_error";
  static const String actionsLoadCopySuccess = "actions.load_copy_success";
  static const String actionsNewDocument = "actions.new_document";
  static const String actionsNext = "actions.next";
  static const String actionsNo = "actions.no";
  static const String actionsOpen = "actions.open";
  static const String actionsOpenDocument = "actions.open_document";
  static const String actionsOpenSettings = "actions.open_settings";
  static const String actionsPickImage = "actions.pick_image";
  static const String actionsPreviewDocument = "actions.preview_document";
  static const String actionsProceedToPayment = "actions.proceed_to_payment";
  static const String actionsReset = "actions.reset";
  static const String actionsRetryAction = "actions.retry_action";
  static const String actionsReturnToTemplates = "actions.return_to_templates";
  static const String actionsSave = "actions.save";
  static const String actionsSaveCopyTitle = "actions.save_copy_title";
  static const String actionsSearch = "actions.search";
  static const String actionsSelectDateTime = "actions.select_date_time";
  static const String actionsSend = "actions.send";
  static const String actionsShare = "actions.share";
  static const String actionsShowLess = "actions.show_less";
  static const String actionsShowMenu = "actions.show_menu";
  static const String actionsShowMore = "actions.show_more";
  static const String actionsSignDocument = "actions.sign_document";
  static const String actionsStartProcess = "actions.start_process";
  static const String actionsSubmit = "actions.submit";
  static const String actionsTryAgainLater = "actions.try_again_later";
  static const String actionsUpload = "actions.upload";
  static const String actionsUploadTemplate = "actions.upload_template";
  static const String actionsUseCopy = "actions.use_copy";
  static const String actionsView = "actions.view";
  static const String actionsYes = "actions.yes";

  // --- Labels ---
  static const String labelsActions = "labels.actions";
  static const String labelsAllTemplates = "labels.all_templates";
  static const String labelsCm = "labels.cm";
  static const String labelsCommon = "labels.common";
  static const String labelsConfigureTemplateFields = "labels.configure_template_fields";
  static const String labelsDefaultValue = "labels.default_value";
  static const String labelsDetectedFields = "labels.detected_fields";
  static const String labelsDocuments = "labels.documents";
  static const String labelsEnableMultipleChoice = "labels.enable_multiple_choice";
  static const String labelsEnterTemplateName = "labels.enter_template_name";
  static const String labelsError = "labels.error";
  static const String labelsExportConfiguration = "labels.export_configuration";
  static const String labelsExportProgress = "labels.export_progress";
  static const String labelsFieldKey = "labels.field_key";
  static const String labelsFieldName = "labels.field_name";
  static const String labelsGeneral = "labels.general";
  static const String labelsGeneralInfo = "labels.general_info";
  static const String labelsHeight = "labels.height";
  static const String labelsImportConfiguration = "labels.import_configuration";
  static const String labelsImportExportConfiguration = "labels.import_export_configuration";
  static const String labelsInches = "labels.inches";
  static const String labelsInputFieldName = "labels.input_field_name";
  static const String labelsInputOptions = "labels.input_options";
  static const String labelsInputSummary = "labels.input_summary";
  static const String labelsInputType = "labels.input_type";
  static const String labelsLogDetails = "labels.log_details";
  static const String labelsLogHistory = "labels.log_history";
  static const String labelsMultiple = "labels.multiple";
  static const String labelsNewTemplate = "labels.new_template";
  static const String labelsOptions = "labels.options";
  static const String labelsOverview = "labels.overview";
  static const String labelsPrompt = "labels.prompt";
  static const String labelsQuickActions = "labels.quick_actions";
  static const String labelsRecentTemplates = "labels.recent_templates";
  static const String labelsRequired = "labels.required";
  static const String labelsResponse = "labels.response";
  static const String labelsSection = "labels.section";
  static const String labelsSettings = "labels.settings";
  static const String labelsSingle = "labels.single";
  static const String labelsSupportedFileTypes = "labels.supported_file_types";
  static const String labelsTemplateFill = "labels.template_fill";
  static const String labelsTemplateName = "labels.template_name";
  static const String labelsTemplates = "labels.templates";
  static const String labelsThemeColor = "labels.theme_color";
  static const String labelsTimestamp = "labels.timestamp";
  static const String labelsUnit = "labels.unit";
  static const String labelsUploadDocxFile = "labels.upload_docx_file";
  static const String labelsWidth = "labels.width";

  // --- Messages ---
  static const String messagesConfirmCreateDocument = "messages.confirm_create_document";
  static const String messagesConfirmDeleteAllLogs = "messages.confirm_delete_all_logs";
  static const String messagesConfirmEditDocument = "messages.confirm_edit_document";
  static const String messagesDateFormatInvalid = "messages.date_format_invalid";
  static const String messagesDocumentExportedReadyForDownload = "messages.document_exported_ready_for_download";
  static const String messagesDocumentExportedSuccessfully = "messages.document_exported_successfully";
  static const String messagesDocumentSuccessfullyCreate = "messages.document_successfully_create";
  static const String messagesDragAndDropDocx = "messages.drag_and_drop_docx";
  static const String messagesEnterDateFormat = "messages.enter_date_format";
  static const String messagesEnterTemplateNameHint = "messages.enter_template_name_hint";
  static const String messagesExcelUnsupportedFormat = "messages.excel_unsupported_format";
  static const String messagesExportSummarySuccess = "messages.export_summary_success";
  static const String messagesExtractNoText = "messages.extract_no_text";
  static const String messagesFieldIsRequired = "messages.field_is_required";
  static const String messagesFillInfoBelow = "messages.fill_info_below";
  static const String messagesGeminiApiKeyHint = "messages.gemini_api_key_hint";
  static const String messagesGeminiApiKeyRequired = "messages.gemini_api_key_required";
  static const String messagesGeminiConfigDesc = "messages.gemini_config_desc";
  static const String messagesGeminiModelDesc = "messages.gemini_model_desc";
  static const String messagesImportFromFileSuccess = "messages.import_from_file_success";
  static const String messagesImportSetting = "messages.import_setting";
  static const String messagesInputTextHint = "messages.input_text_hint";
  static const String messagesNameTheDocumentExported = "messages.name_the_document_exported";
  static const String messagesNoLogsFound = "messages.no_logs_found";
  static const String messagesPickFolderToExport = "messages.pick_folder_to_export";
  static const String messagesReviewAndConfigureFields = "messages.review_and_configure_fields";
  static const String messagesReviewBeforeExport = "messages.review_before_export";
  static const String messagesSettingExported = "messages.setting_exported";
  static const String messagesSettingsSaveSuccess = "messages.settings_save_success";
  static const String messagesSingleLineTextHint = "messages.single_line_text_hint";
  static const String messagesUploadTemplate = "messages.upload_template";

  // --- Settings ---
  static const String settingsGeminiApiKey = "settings.gemini.api_key";
  static const String settingsGeminiEnableLogging = "settings.gemini.enable_logging";
  static const String settingsGeminiModel = "settings.gemini.model";
  static const String settingsGeminiOpenLogs = "settings.gemini.open_logs";
  static const String settingsGeminiSaveBtn = "settings.gemini.save_btn";
  static const String settingsGeminiTitle = "settings.gemini.title";
  static const String settingsGeneralEnglish = "settings.general.english";
  static const String settingsGeneralLanguage = "settings.general.language";
  static const String settingsGeneralTitle = "settings.general.title";
  static const String settingsGeneralVietnamese = "settings.general.vietnamese";

}
