import 'dart:convert';
import 'dart:io';

void main() async {
  // Paths are relative to the root of the project
  final jsonFile = File('apps/assets/translations/en-US.json');
  final outputFile = File('apps/lib/const/src/app_lang.dart');

  if (!await jsonFile.exists()) {
    print('Error: en-US.json not found at ${jsonFile.path}');
    return;
  }

  final content = await jsonFile.readAsString();
  final Map<String, dynamic> data = jsonDecode(content);

  final Map<String, String> keys = {};
  _flatten(data, '', keys);

  final StringBuffer buffer = StringBuffer();
  buffer.writeln('// This file is automatically generated. Do not edit manually.');
  buffer.writeln();
  buffer.writeln('/// Contains all localization keys used in the application.');
  buffer.writeln('abstract class AppLang {');
  buffer.writeln('  AppLang._();');
  buffer.writeln();

  // Sort keys alphabetically to ensure consistent generation
  final sortedKeys = keys.keys.toList()..sort();

  // Group keys by top-level section
  final sections = <String, List<String>>{};
  for (final key in sortedKeys) {
    final firstDot = key.indexOf('.');
    final section = firstDot == -1 ? 'general' : key.substring(0, firstDot);
    sections.putIfAbsent(section, () => []).add(key);
  }

  // Move 'general' to the top if it exists
  final sectionNames = sections.keys.toList()..sort();
  if (sectionNames.contains('general')) {
    sectionNames.remove('general');
    sectionNames.insert(0, 'general');
  }

  for (final section in sectionNames) {
    final sectionKeys = sections[section]!;
    buffer.writeln('  // --- ${section[0].toUpperCase()}${section.substring(1)} ---');
    for (final key in sectionKeys) {
      final varName = _toCamelCase(key);
      buffer.writeln('  static const String $varName = "$key";');
    }
    buffer.writeln();
  }

  buffer.writeln('}');

  await outputFile.writeAsString(buffer.toString());
  print('Successfully generated ${outputFile.path}');
}

void _flatten(Map<String, dynamic> map, String prefix, Map<String, String> result) {
  map.forEach((key, value) {
    final newKey = prefix.isEmpty ? key : '$prefix.$key';
    if (value is Map<String, dynamic>) {
      _flatten(value, newKey, result);
    } else {
      result[newKey] = value.toString();
    }
  });
}

String _toCamelCase(String key) {
  final parts = key.split(RegExp(r'[\._]'));
  if (parts.isEmpty) return '';
  
  final buffer = StringBuffer(parts[0]);
  for (int i = 1; i < parts.length; i++) {
    final part = parts[i];
    if (part.isEmpty) continue;
    buffer.write(part[0].toUpperCase() + part.substring(1));
  }
  return buffer.toString();
}
